### ISSUE TITLE
Doesn't work with PHP 7

### ISSUE THREAD

**Issue by mtricht** [ztec/JpGraph#10]
Version 4.x.x does work with PHP 7.

**Comment by necrogami** [comment]
Actually it doesn't work with 7.0.2+
as self named constructors now throw a php exception.

the ENTIRE library would need re-written and brought up to PSR-2 and Namespacing as well as removing the multiple classes per file.

**Comment by ztec** [comment]
I've update to latest version that is said compatible with php7 on the website.

**Comment by necrogami** [comment]
This throws a bunch of exceptions for self named constructors.

**Comment by ztec** [comment]
Do you have the exception itself ?

**Comment by necrogami** [comment]
https://puu.sh/upbHk/a2fc7639bc.png

**Comment by nynka** [comment]
Yup I also got this deprecated notice, LinePlot class in jpgraph_line.php has an old style constructor:
```php
function LinePlot($datay,$datax=false) {
```
should be:
```php
public function __construct($datay, $datax = false)
{
```
And as @necrogami pointed out, the whole library is quite outdated in terms of PSRs.

**Comment by necrogami** [comment]
Indeed, multiple classes per file no namespacing, outdated constructors. The whole infrastructure would need to be re-written but jpgraph isn't really opensource so it's not nearly as worth it.

**Comment by ztec** [comment]
All issues come from JpGraph source code. I canot change anything regarding this part.  I thinks those issue will stay.

All I can do is update this repository if new version is released. I don't check often.
